### ISSUE TITLE
directory structure to match routing

### ISSUE THREAD

**Issue by sdebaun** [sdebaun/sparks-cyclejs#25]
Proposed change of directory structure:

```
/src
  /app
    index.js (currently App.js)
    /Admin (as is)
    /Dash (Dash.js when it expands to have multiple subpages)
    /Confirm.js (single page route at /confirm)
    /Landing.js (same)
  /components (everything else remains for now)
```

the notion is that everything in /app should be unique to wherever it is in the routing tree.  maybe /routes is a better name?

still thinking on how to organize everything else... i see three kinds of things so far:
- domain-specific components, things like a ProjectList that might be reused on different routes, or even from other components, but expect and return streams that are specific to a problem domain.
- generic components, like Cropper, Dropper, and when we eventually extract the Tabs into their own component instead of just a hacky render + css.
- render functions, these are dom-specific shortcuts that will be frequently reused.  these should probably behave like div() and other snabbdom helpers.

@TylorS thoughts?

**Comment by TylorS** [comment]
I'm right there 100% on restructuring a bit to match how we are routing, I don't see why we should hesitate to do that. It will make it easier to navigate around. I think I like `/routes` better just because that explains the hierarchy a bit better, as _everything_ is the App.

> domain-specific components

I think the best bet for now is to keep them domain-specific, and refactor as time goes on and we know how to properly abstract them. e.g. We have more information on how we're going to use them, at which point they will probably be made more of a generic component with optional parameters sort of like snabbdom-material.

> generic components

Just keeping those inside of the components folder makes plenty of sense

> render functions

I think your `/helpers/dom.js` could eventually be created into a `/helpers/dom/...` folder to accommodate more generic renderFoo() functions, or perhaps a `/view` folder could be created specifically for those?
